import { of } from 'rxjs';

export class EventServiceStub {
    load() {
        return of([
            {
                "event_id": "632",
                "post_id": "13776",
                "event_slug": "unity-camp-3-2024",
                "event_owner": "11",
                "event_status": "1",
                "event_name": "Unity Camp 3 2024",
                "event_start_date": "2024-07-05",
                "event_end_date": "2024-07-07",
                "event_start_time": "15:00:00",
                "event_end_time": "15:00:00",
                "event_all_day": "0",
                "event_start": "2024-07-05 13:00:00",
                "event_end": "2024-07-07 13:00:00",
                "event_timezone": "Europe/Copenhagen",
                "post_content": "<div><a href=\"https://www.nadanmark.dk/wp-content/uploads/2024/03/Unity-Camp-3-2024-flyer-scaled.jpg\" target=\"_blank\" rel=\"noopener\"><img class=\"alignnone wp-image-13777 size-medium\" src=\"https://www.nadanmark.dk/wp-content/uploads/2024/03/Unity-Camp-3-2024-flyer-212x300.jpg\" alt=\"\" width=\"212\" height=\"300\" /></a></div>\r\n<div><a href=\"https://www.nadanmark.dk/wp-content/uploads/2024/03/Unity-Camp-3-2024-flyer.pdf\">Unity Camp 3 2024 flyer</a></div>\r\n<div></div>\r\n<div>Unity Camp 3 - 2024</div>\r\n<div></div>\r\n<div>5-7 juli 2024</div>\r\n<div>Adresse:\r\nSårupvej 62\r\n7730 Hanstholm</div>\r\n<div></div>\r\n<div>Forregistrering t.o.m. 28/6 på <a href=\"http://nakonvent.dk/\" target=\"_blank\" rel=\"noopener\">nakonvent.dk</a></div>\r\n<div>\r\n\r\nPris 150 kr inkl. morgenmad\r\n\r\n</div>\r\n<div>Billet til aftensmad lørdag, pris 100 kr.</div>",
                "event_rsvp": "0",
                "event_rsvp_date": null,
                "event_rsvp_time": null,
                "event_rsvp_spaces": null,
                "event_spaces": null,
                "event_private": "0",
                "location_id": "87",
                "recurrence_id": null,
                "event_date_created": "2024-03-31 19:02:14",
                "event_date_modified": "2024-04-03 20:42:22",
                "recurrence": "0",
                "recurrence_interval": null,
                "recurrence_freq": null,
                "recurrence_byday": null,
                "recurrence_byweekno": null,
                "recurrence_days": null,
                "recurrence_rsvp_days": null,
                "blog_id": "0",
                "group_id": "0",
                "event_parent": null,
                "event_language": "da_DK",
                "event_translation": "0",
                "event_location_type": null,
                "event_active_status": "1",
                "category_id": "53",
                "category_name": "Bedringsarrangementer",
                "category_slug": "bedringsarrangement",
                "url": "https://www.nadanmark.dk/events/unity-camp-3-2024"
              },
              {
                "event_id": "513",
                "post_id": "12420",
                "event_slug": "eccna-39-helsinki-the-new-way-of-life",
                "event_owner": "11",
                "event_status": "1",
                "event_name": "ECCNA 39- HELSINKI- THE NEW WAY OF LIFE",
                "event_start_date": "2024-07-12",
                "event_end_date": "2024-07-14",
                "event_start_time": "00:00:00",
                "event_end_time": "23:59:59",
                "event_all_day": "1",
                "event_start": "2024-07-11 22:00:00",
                "event_end": "2024-07-14 21:59:59",
                "event_timezone": "Europe/Copenhagen",
                "post_content": "<img class=\"alignnone size-medium wp-image-12421\" src=\"https://www.nadanmark.dk/wp-content/uploads/2023/08/Flyers-ECCNA39-12.-14.-juli-2023-Finland-212x300.jpg\" alt=\"\" width=\"212\" height=\"300\" />\r\n\r\n<img class=\"alignnone size-medium wp-image-12422\" src=\"https://www.nadanmark.dk/wp-content/uploads/2023/08/Call-for-speakere-ECCNA-39-2024-212x300.jpg\" alt=\"\" width=\"212\" height=\"300\" />",
                "event_rsvp": "0",
                "event_rsvp_date": null,
                "event_rsvp_time": null,
                "event_rsvp_spaces": null,
                "event_spaces": null,
                "event_private": "0",
                "location_id": "75",
                "recurrence_id": null,
                "event_date_created": "2023-08-18 13:04:42",
                "event_date_modified": null,
                "recurrence": "0",
                "recurrence_interval": null,
                "recurrence_freq": null,
                "recurrence_byday": null,
                "recurrence_byweekno": null,
                "recurrence_days": null,
                "recurrence_rsvp_days": null,
                "blog_id": "0",
                "group_id": "0",
                "event_parent": null,
                "event_language": "da_DK",
                "event_translation": "0",
                "event_location_type": null,
                "event_active_status": "1",
                "category_id": "53",
                "category_name": "Bedringsarrangementer",
                "category_slug": "bedringsarrangement",
                "url": "https://www.nadanmark.dk/events/eccna-39-helsinki-the-new-way-of-life"
              }
        ]);
    }
}