name: Verify pull request

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: verify-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  typecheck:
    uses: ./.github/workflows/check-types.yml

  test:
    uses: ./.github/workflows/test-unit.yml
